-- MySQL Script generated by MySQL Workbench
-- Sun Jun 22 23:27:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema acc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema acc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `acc` ;

-- -----------------------------------------------------
-- Table `acc`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acc`.`turma` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `acc`.`grupo_estagio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acc`.`grupo_estagio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(7) NOT NULL,
  `turma_id` INT NOT NULL,
  `dia_semana` ENUM('Quinta', 'Sexta') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `turma_id` (`turma_id` ASC) VISIBLE,
  CONSTRAINT `grupo_estagio_ibfk_1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `acc`.`turma` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `acc`.`tb_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acc`.`tb_alunos` (
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  `turma_id` INT NULL DEFAULT NULL,
  `grupo_id` INT NULL DEFAULT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`),
  INDEX `turma_id` (`turma_id` ASC) VISIBLE,
  INDEX `grupo_id` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `tb_alunos_ibfk_1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `acc`.`turma` (`id`),
  CONSTRAINT `tb_alunos_ibfk_2`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `acc`.`grupo_estagio` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `acc`.`tb_professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acc`.`tb_professores` (
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
